server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${PAYMENT_MYSQL_URL}
    username: ${PAYMENT_MYSQL_USERNAME}
    password: ${PAYMENT_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# TODO 프론트 URL 나온 후 수정 필요. 그 전까지 임시 html 사용
app:
  frontend:
    success-url: /success-temp.html
    fail-url: /fail-temp.html